packages:
  - packages/*
  - site

catalog:
  "@tanstack/query-core": "5.49.1"
  "@tanstack/react-query": "5.49.2"
  "@testing-library/dom": "10.4.0"
  "@testing-library/react": "16.0.1"
  "@types/react": "18.3.1"
  "@types/react-dom": "18.3.0"
  react-dom: "18.3.1"
  react: "18.3.1"
  